/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos;

/**
 *
 * @author Hèctor
 */
public class jFasiento extends javax.swing.JFrame {

    /**
     * Creates new form jFasiento
     */
    public jFasiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jAsiento = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRBlibre = new javax.swing.JRadioButton();
        jRBocupado = new javax.swing.JRadioButton();
        precio = new javax.swing.JLabel();
        jTextprecio = new javax.swing.JTextField();
        jBaceptar = new javax.swing.JButton();
        jBbuscar = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        Ubicacion = new javax.swing.JLabel();
        RBventanilla = new javax.swing.JRadioButton();
        RBpasillo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jAsiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jAsiento.setText("Asientos");

        id.setText("ID");

        jLabel1.setText("Disponibilidad");

        jRBlibre.setBackground(new java.awt.Color(204, 204, 204));
        jRBlibre.setText("Libre");
        jRBlibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBlibreActionPerformed(evt);
            }
        });

        jRBocupado.setBackground(new java.awt.Color(204, 204, 204));
        jRBocupado.setText("Ocupado");
        jRBocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBocupadoActionPerformed(evt);
            }
        });

        precio.setText("Precio");

        jBaceptar.setText("Aceptar");

        jBbuscar.setText("Buscar");

        finalizar.setText("Finalizar");

        Ubicacion.setText("Ubicacion");

        RBventanilla.setBackground(new java.awt.Color(204, 204, 204));
        RBventanilla.setText("Ventanilla");
        RBventanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBventanillaActionPerformed(evt);
            }
        });

        RBpasillo.setBackground(new java.awt.Color(204, 204, 204));
        RBpasillo.setText("Pasillo");
        RBpasillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBpasilloActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jAsiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRBlibre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRBocupado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(precio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextprecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBaceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jBbuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(finalizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Ubicacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(RBventanilla, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(RBpasillo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jAsiento))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBaceptar)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(id)
                                .addComponent(jLabel1)
                                .addComponent(precio)
                                .addComponent(Ubicacion)))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(RBventanilla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RBpasillo))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jRBlibre)
                                .addGap(22, 22, 22)
                                .addComponent(jRBocupado))
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBbuscar)
                                .addComponent(jTextprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14)
                .addComponent(finalizar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAsiento)
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRBlibre)
                    .addComponent(jRBocupado))
                .addGap(4, 4, 4)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ubicacion)
                    .addComponent(RBventanilla)
                    .addComponent(RBpasillo))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio)
                    .addComponent(jTextprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaceptar)
                    .addComponent(jBbuscar)
                    .addComponent(finalizar))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBlibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBlibreActionPerformed
       jRBocupado.setEnabled(false); // TODO add your handling code here:
    }//GEN-LAST:event_jRBlibreActionPerformed

    private void jRBocupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBocupadoActionPerformed
       jRBlibre.setEnabled(false); // TODO add your handling code here:
    }//GEN-LAST:event_jRBocupadoActionPerformed

    private void RBpasilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBpasilloActionPerformed
        RBventanilla.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBpasilloActionPerformed

    private void RBventanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBventanillaActionPerformed
        RBpasillo.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_RBventanillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFasiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBpasillo;
    private javax.swing.JRadioButton RBventanilla;
    private javax.swing.JLabel Ubicacion;
    private javax.swing.JButton finalizar;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jAsiento;
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBlibre;
    private javax.swing.JRadioButton jRBocupado;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextprecio;
    private javax.swing.JLabel precio;
    // End of variables declaration//GEN-END:variables
}
